# Generated by Django 4.2.7 on 2023-11-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='descriprtion',
            new_name='description',
        ),
    ]
